Repository DigitalKin-ai/service-apis, pull requests merged in 2024-09, with the labels that each got.

#30 fix(service): fix assistant request
  proto/digitalkin/project/v1/edge.proto
  proto/digitalkin/project/v1/node.proto
  proto/digitalkin/project/v1/workflow.proto
  proto/digitalkin/setup/v1/assistant.proto
  proto/digitalkin/setup/v1/setup.proto
  proto/digitalkin/setup/v1/setup_service.proto
  proto/digitalkin/setup/v1/tool.proto
Labels: ⚠️ high priority, 💎 refacto, 🚀 ok for Reviews, 🚠 infrastructure

#31 fix(service): Fix login
  proto/digitalkin/client/v1/auth.proto
Labels: ⚠️ high priority, 🐛 bug, 🚀 ok for Reviews

#35 Remove Metadata
  proto/digitalkin/module/v1/lifecycle.proto
Labels: 🚀 ok for Reviews

#36 Update Validate package
  .protolint.yaml
  proto/buf.yaml
  proto/buf/validate/expression.proto
  proto/buf/validate/priv/private.proto
  proto/buf/validate/validate.proto
  proto/digitalkin/module/v1/information.proto
  proto/digitalkin/module/v1/lifecycle.proto
  proto/digitalkin/module/v1/monitoring.proto
  proto/digitalkin/module_registry/v1/action.proto
  proto/digitalkin/module_registry/v1/monitoring.proto
  proto/digitalkin/module_registry/v1/registration.proto
  proto/validate/validate.proto
Labels: 🎛️ dependencies, 💓 enhancement, 🚀 ok for Reviews
