Repository DigitalKin-ai/service-apis, pull requests merged in 2024-11, with the labels that each got.

#39 refacto(service): Start refacto payment
  proto/digitalkin/payment/v1/checkout.proto
  proto/digitalkin/payment/v1/currency.proto
  proto/digitalkin/payment/v1/metadata.proto
  proto/digitalkin/payment/v1/payment_service.proto
  proto/digitalkin/payment/v1/price.proto
  proto/digitalkin/payment/v1/product.proto
  proto/digitalkin/payment/v1/recurring.proto
  proto/digitalkin/payment/v1/subscription.proto
Labels: 💎 refacto, 🚀 ok for Reviews

#42 Updating setup and adding module data inside storage
  proto/buf.gen.py.yaml
  proto/buf.py.yaml
  proto/digitalkin/module/v1/lifecycle.proto
  proto/digitalkin/setup/v2/setup.proto
  proto/digitalkin/setup/v2/setup_service.proto
  proto/digitalkin/storage/v1/data.proto
  proto/digitalkin/storage/v1/module_data_service.proto
Labels: 💓 enhancement, 🚀 ok for Reviews

#43 refacto(service): Start refacto services
  proto/digitalkin/admin/v1/admin.proto
  proto/digitalkin/auth/v1/auth.proto
  proto/digitalkin/client/v1/client_service.proto
  proto/digitalkin/client/v1/organization.proto
  proto/digitalkin/client/v1/ticketing.proto
  proto/digitalkin/client/v1/user.proto
  proto/digitalkin/common/v1/common.proto
  proto/digitalkin/group/v1/group_service.proto
  proto/digitalkin/group/v1/organization.proto
  proto/digitalkin/project/v1/kin.proto
  proto/digitalkin/project/v1/project_service.proto
  proto/digitalkin/store/v1/block.proto
  proto/digitalkin/store/v1/card.proto
  proto/digitalkin/store/v1/datasheet.proto
  proto/digitalkin/store/v1/details.proto
  proto/digitalkin/store/v1/faq_block.proto
  proto/digitalkin/store/v1/review.proto
  proto/digitalkin/store/v1/stepper_block.proto
  proto/digitalkin/store/v1/store.proto
  proto/digitalkin/store/v1/store_service.proto
  proto/digitalkin/store/v1/tag.proto
  proto/digitalkin/store/v1/text_block.proto
Labels: 💎 refacto
