Repository DigitalKin-ai/service-apis, pull requests merged in 2024-08, with the labels that each got.

#25 feat(service): Add ChatBot
  proto/digitalkin/kin/v1/kin_response.proto
Labels: ⚠️ high priority, 💓 enhancement

#24 refacto(service): Refacto kin service. Split in two service Store and Project
  .github/workflows/CI.yml
  .gitignore
  .protolint.yaml
  README.md
  proto/buf.yaml
  proto/digitalkin/client/v1/admin.proto
  proto/digitalkin/client/v1/auth.proto
  proto/digitalkin/client/v1/organization.proto
  proto/digitalkin/client/v1/ticketing.proto
  proto/digitalkin/client/v1/user.proto
  proto/digitalkin/common/v1/common.proto
  proto/digitalkin/kin/v1/kin.proto
  proto/digitalkin/kin/v1/kin_response.proto
  proto/digitalkin/kin/v1/kin_thread.proto
  proto/digitalkin/kin/v1/kin_workflow.proto
  proto/digitalkin/payment/v1/stripe.proto
  proto/digitalkin/project/v1/activity.proto
  proto/digitalkin/project/v1/edge.proto
  proto/digitalkin/project/v1/kin.proto
  proto/digitalkin/project/v1/message.proto
  proto/digitalkin/project/v1/node.proto
  proto/digitalkin/project/v1/project_service.proto
  proto/digitalkin/project/v1/response.proto
  proto/digitalkin/project/v1/thread.proto
  proto/digitalkin/project/v1/workflow.proto
  proto/digitalkin/storage/v1/s3_storage.proto
  proto/digitalkin/store/v1/block.proto
  proto/digitalkin/store/v1/card.proto
  proto/digitalkin/store/v1/details.proto
  proto/digitalkin/store/v1/faq_block.proto
  proto/digitalkin/store/v1/review.proto
  proto/digitalkin/store/v1/stepper_block.proto
  proto/digitalkin/store/v1/store.proto
  proto/digitalkin/store/v1/store_service.proto
  proto/digitalkin/store/v1/tag.proto
  proto/digitalkin/store/v1/text_block.proto
  proto/google/api/annotations.proto
  proto/google/api/field_behavior.proto
  proto/google/protobuf/any.proto
  proto/google/protobuf/descriptor.proto
  proto/google/protobuf/empty.proto
  proto/google/protobuf/timestamp.proto
Labels: 💎 refacto, 💓 enhancement

#28 Ajout des proto gRPC pour le SDK Python
  .protolint.yaml
  README.md
  proto/buf.gen.py.yaml
  proto/digitalkin/module/v1/information.proto
  proto/digitalkin/module/v1/lifecycle.proto
  proto/digitalkin/module/v1/module_service.proto
  proto/digitalkin/module/v1/monitoring.proto
  proto/digitalkin/module_registry/v1/action.proto
  proto/digitalkin/module_registry/v1/module_registry_service.proto
  proto/digitalkin/module_registry/v1/registration.proto
  proto/google/protobuf/struct.proto
  proto/validate/validate.proto
Labels: 🎛️ dependencies, 💓 enhancement, 🚀 ok for Reviews

#29 feat(service): Add assistant service
  proto/digitalkin/project/v1/kin.proto
  proto/digitalkin/project/v1/message.proto
  proto/digitalkin/project/v1/thread.proto
  proto/digitalkin/setup/v1/assistant.proto
  proto/digitalkin/setup/v1/setup.proto
  proto/digitalkin/setup/v1/setup_service.proto
  proto/digitalkin/setup/v1/tool.proto
Labels: ⚠️ high priority, 💎 refacto, 💓 enhancement, 🚀 ok for Reviews
